
export const APP_MENU_CHANGE = 'APP_MENU_CHANGE';
export const DUPLICATE_APP_ACTION = 'DUPLICATE_APP_ACTION';
export const UPDATE_NOTIFCATION = 'UPDATE_NOTIFCATION';
export const UPDATE_BREADCRUMB = 'UPDATE_BREADCRUMB';

