export const MAIL_MESSAGE_LOADING = 'MAIL_MESSAGE_LOADING';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const SEND_JOIN_REQUEST = 'SEND_JOIN_REQUEST';
export const ANSWER_JOIN_REQUEST = 'ANSWER_JOIN_REQUEST';
export const REQUEST_LIST_LOADING = 'REQUEST_LIST_LOADING';
export const SAVE_SENT_MESSAGE = 'SAVE_SENT_MESSAGE';
export const DUPLICATE_COURRIER_ACTION = 'DUPLICATE_COURRIER_ACTION';
