export const MAIL_MESSAGE_LOADING = 'MAIL_MESSAGE_LOADING';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const SAVE_SENT_MESSAGE = 'SAVE_SENT_MESSAGE';
export const DUPLICATE_MAIL_ACTION = 'DUPLICATE_MAIL_ACTION';
