
export const VISION_SAVED = 'VISION_SAVED';
export const VISION_SAVE_LOADING = 'VISION_SAVE_LOADING';
export const VISION_HISTORY_LOADING = 'VISION_HISTORY_LOADING';
export const VISION_LIST = 'VISION_LIST';
export const VISION_LIST_LOADING = 'VISION_LIST_LOADING';
export const VISION_FS_LOADING = 'VISION_FS_LOADING';
export const VISION_STAT_LOADING = 'VISION_STAT_LOADING';
export const SAVE_CONTRIBUTION_LOADING = 'SAVE_CONTRIBUTION_LOADING';
export const BRANCH_LIST_LOADING = 'BRANCH_LIST_LOADING';
export const FILE_READ_LOADING = 'FILE_READ_LOADING';

export const DUPLICATE_VISION_ACTION = 'DUPLICATE_VISION_ACTION';
